import socket
from datetime import datetime, timezone
import os
import psutil
import subprocess
import importlib.metadata
import platform
import getpass
from jinja2 import Environment
import pathlib
import json
def getGitInfo(debug):
    gitCommands = {
        "git tag": ["git", "describe", "--tags", "--always"],
         "git branch": ["git", "rev-parse", "--abbrev-ref", "HEAD"],
         "dirtyFiles": ["git", "status", "--porcelain"]
    }

    output = dict()

    for key, command in gitCommands.items():
        gitInfo = subprocess.run(
            command,
            capture_output=True,
            text=True
        )

        if gitInfo.returncode != 0:
            if debug:
                print(gitInfo.stderr.decode())
                exit()
            output[key] = f"Unable to obtain {key}"
        
        else:
            output[key] = gitInfo.stdout.splitlines()
    
    return output

def getDependcies(debug):
    packageInfo = subprocess.run(
        ["pip", "freeze"],
        capture_output=True,
        text=True
    )
    
    if packageInfo.returncode != 0:
        if debug:
            print(packageInfo.stderr.decode())
            exit()
        return ["Unable to get pip packages"]
    
    return packageInfo.stdout.splitlines()

def writeMetaData(args):
    resultsDir = pathlib.Path(__file__).resolve().parent/f"../Run/{args.resultsDirectory}"
    resultsDir.mkdir(parents=True, exist_ok=True)
    
    dateTime = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "").split("T")

    with open(resultsDir/"MetaData.json", "w") as fp:
        json.dump(
            {
                "comment": "This file was automatically generated by BLOOP",
                "benchmarkGenerator": args.bmGeneratorModule,
                "benchmarkType": args.benchmarkType,
                "benchmarkFilePath": args.benchmarkFilePath,
                "Model": args.modelDirectory,
                "Results directory": args.resultsDirectory,
                "date": dateTime[0],
                "time (UTC)": dateTime[1],
                "user": getpass.getuser(),
                "host machine": socket.gethostname(),
                **getGitInfo(args.debug),
                "Python Version": platform.python_version(),
                "pip packages":  getDependcies(args.debug),
                "command": " ".join(psutil.Process(os.getpid()).cmdline()),
                "all cmd line args":  vars(args)
            },
        fp,
        indent=2
        )
    return None

