import getpass
import json
import os
import pathlib
import platform
import socket
import subprocess
from datetime import datetime, timezone

import psutil


def writeMetaData(args):
    resultsDir = pathlib.Path(__file__).resolve().parent/f"../Run/{args.resultsDirectory}"
    resultsDir.mkdir(parents=True, exist_ok=True)
    
    dateTime = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "").split("T")
    with open(resultsDir/"MetaData.json", "w") as fp:
        json.dump(
            {
                "comment": "This file was automatically generated by BLOOP",
                "benchmarkGenerator": args.bmGeneratorModule,
                "benchmarkType": args.benchmarkType,
                "benchmarkFilePath": args.benchmarkFilePath,
                "Model": args.modelDirectory,
                "Results directory": args.resultsDirectory,
                "date": dateTime[0],
                "time (UTC)": dateTime[1],
                "user": getpass.getuser(),
                "host machine": socket.gethostname(),
                **getGitInfo(args.debug),
                "Python Version": platform.python_version(),
                "pip packages":  getDependcies(args.debug),
                "command": " ".join(psutil.Process(os.getpid()).cmdline()),
                "all cmd line args":  vars(args)
            },
        fp,
        indent=2
        )

def getGitInfo(debug):
    return {
        key: subprocess.run(
            command, 
            capture_output=True, 
            text=True).stdout.splitlines()
        for key, command in {
            "git tag": ["git", "describe", "--tags", "--always"],
            "git branch": ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            "dirty files": ["git", "status", "--porcelain"],
        }.items()
    }


def getDependcies(debug):
    return subprocess.run(
        ["pip", "freeze"],
        capture_output=True,
        text=True,
        check=True
    ).stdout.splitlines()

