import socket
from datetime import datetime, timezone
import os
import psutil
import subprocess
import importlib.metadata
import platform
import getpass
from jinja2 import Environment

def getGitInfo(debug):
    gitCommands = {
        "tag": ["git", "describe", "--tags", "--always"],
         "branch": ["git", "rev-parse", "--abbrev-ref", "HEAD"],
         "dirtyFiles": ["git", "status", "--porcelain"]
    }

    output = dict()

    for key, command in gitCommands.items():
        gitInfo = subprocess.run(
            command,
            capture_output=True,
        )

        if gitInfo.returncode != 0:
            if debug:
                print(gitInfo.stderr.decode())
                exit()
            output[key] = f"Unable to obtain {key}"
        
        else:
            output[key] = gitInfo.stdout.decode().strip().splitlines()
    
    return output

def getImportantDependcies():
    packages = ["nlopt", "pdg", "cython", "numpy", "sympy", "jinja2"]
    
    output = dict()

    for package in packages:
        output[package] = importlib.metadata.version(package)
    
    return output


def writeMetaData(args):
    with open("metaData.txt", "w") as fp:
        fp.write(Environment().from_string("""\
This file was automaticaly generated by BLOOP on {{dateTime[0]}}-{{dateTime[1]}} (UTC) by {{user}} on {{machine}}. 
cmdline that generated this file: {{cmd}}

This meta data is for a BLOOP run which will generate benchmarks via {{args['bmGeneratorModule']}}, mode {{args['benchmarkType']}}
The benchmarks will be saved to {{args['benchmarkFilePath']}} (note this is relative to model dir)
Results from the parameter scan will be saved to {{args['resultsDirector']}}/{{args['scanResultsName']}} (relative to Run)

BLOOP version: {{gitInfo.tag[0]}} 
Running on branch: {{gitInfo.branch[0]}}
Uncommited files:
{%- for file in gitInfo.dirtyFiles %}
{{file}}
{%- endfor %}

Critical package versions:
--Python: {{pythonVersion}}
{%- for package, version in packagesVersions.items() %}
--{{package}}: {{version}}
{%- endfor %}

Complete list of cmdline args:
{%- for key, val in args.items() %}
--{{key}}: {{val}}
{%- endfor %}
\n
""").render(
    args=vars(args),
    dateTime = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "").split("T"),
    user= getpass.getuser(),
    machine =  socket.gethostname(),
    gitInfo = getGitInfo(args.debug),
    pythonVersion = platform.python_version(),
    packagesVersions = getImportantDependcies(),
    cmd = " ".join(psutil.Process(os.getpid()).cmdline()),
    )
)
    return None
