name: Test pip installation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pipInstall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pip install BLOOP
        run: pip install -e .
      - name: check installation
        run: bloop --help
