name: Ruff Linter
on:
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: python3 -m ruff check $PWD/Source || exit 0
      #- name: Upload diff files
      #  if: failure()
      #  uses: actions/upload-artifact@v4
      #  with:
      #      name: integration-test-diffs
      #      path: Run/*Diff.txt
