name: Ruff Linter
on:
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: ruff version 
        run: ruff --version
      - name: Run Ruff
        run: python3 -m ruff check Source/ || exit 0
